### ISSUE TITLE
Bugs list

### ISSUE THREAD

**Issue by michael-collins** [LRNWebComponents/hax-desktop-app#5]
- [x] Video embeds do not work consistently with tool bars. The tool bars don't always reappear. Saving the page, and doing Command+R to reload seems to fix it.
- [ ] Selection. When attempting to select more than one word, and make an inline gizmo (OER, or otherwise) it tends to only see portions of the selection. Possibly a selection marker issue?
- [x] **List elements don't quite work.** When trying to add a second item to a numbered list, it creates a new paragraph instead. Shift return doesn't not seem to alter the behavior.

**Comment by btopro** [comment]
continuing here in the real repo: https://github.com/LRNWebComponents/hax-body/issues/104
